version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_parking
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: webserver_parking
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: db_parking
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_parking
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
